### PR TITLE
Push semantic ui stuff

### PR DESCRIPTION
**Pull request by Vavarooks**
Hey my sementic ui stuff is here and need to be added to make stuff work :)

### CODE REVIEW

**Comment by Vavarooks** [comment]
This is the chages i made with the new Meterilize database

**Comment by Vavarooks** [comment]
This is the Mterialize stuff that was added

**Comment by Vavarooks** [comment]
Edit the main page for our food recipe/ take out website

**Comment by Vavarooks** [comment]
two more buttons for recipes for home and going our to eat

**Comment by Reila-GitHubUID** [comment]
Approved the initial index.html

**Pull request merged**
